[package]
name = "_1_zk_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version="0.13.4", default-features=false,features=["arithmetic","serde"] }
sha2 = { version="^0.10", default-features=false }
rand = { version="^0.8" }
serde.workspace = true
serde_json.workspace = true

